services:
  - type: web
    name: ararat-auto
    env: node
    buildCommand: cd BACKEND && npm install
    startCommand: cd BACKEND && node server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
